"""add stage_map

Revision ID: 1f6f72eb0400
Revises: 7c3987160332
Create Date: 2026-05-28 13:45:36.046853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6f72eb0400'
down_revision: Union[str, Sequence[str], None] = '7c3987160332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('branch_created', 'pr_opened', 'ci_passed', 'changes_requested', 'pr_approved', 'pr_closed', name='stage_trigger').create(op.get_bind())
    op.create_table('stage_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plane_project_id', sa.String(), nullable=False),
    sa.Column('trigger', postgresql.ENUM('branch_created', 'pr_opened', 'ci_passed', 'changes_requested', 'pr_approved', 'pr_closed', name='stage_trigger', create_type=False), nullable=False),
    sa.Column('plane_state_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plane_project_id', 'trigger', name='uq_stage_map_project_trigger')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_map')
    sa.Enum('branch_created', 'pr_opened', 'ci_passed', 'changes_requested', 'pr_approved', 'pr_closed', name='stage_trigger').drop(op.get_bind())
    # ### end Alembic commands ###
