"""add_config_tables

Revision ID: 2d8d72e8bdbc
Revises: 9719ad73c88b
Create Date: 2026-05-25 20:54:19.140140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8d72e8bdbc'
down_revision: Union[str, Sequence[str], None] = '9719ad73c88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plane_project_id', sa.String(), nullable=False),
    sa.Column('plane_label_id', sa.String(), nullable=False),
    sa.Column('gh_repo', sa.String(), nullable=False),
    sa.Column('gh_label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_module_map',
    sa.Column('plane_module_id', sa.String(), nullable=False),
    sa.Column('plane_project_id', sa.String(), nullable=False),
    sa.Column('gh_repo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('plane_module_id')
    )
    op.create_table('user_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plane_user_id', sa.String(), nullable=False),
    sa.Column('gh_login', sa.String(), nullable=False),
    sa.Column('discord_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_map')
    op.drop_table('repo_module_map')
    op.drop_table('label_map')
    # ### end Alembic commands ###
