"""add_pr_notification_state

Revision ID: 6c902fdc0f2a
Revises: 2d8d72e8bdbc
Create Date: 2026-05-26 10:15:06.187496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c902fdc0f2a'
down_revision: Union[str, Sequence[str], None] = '2d8d72e8bdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_notification_state',
    sa.Column('pr_node_id', sa.String(), nullable=False),
    sa.Column('gh_repo', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('ready_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ready_cycle_id', sa.String(), nullable=False),
    sa.Column('discord_message_id', sa.String(), nullable=True),
    sa.Column('discord_thread_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pr_node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_notification_state')
    # ### end Alembic commands ###
