"""initial schema

Revision ID: 9719ad73c88b
Revises: 
Create Date: 2026-05-20 22:42:21.396018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9719ad73c88b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_issue_link',
    sa.Column('plane_card_id', sa.String(), nullable=False),
    sa.Column('plane_project_id', sa.String(), nullable=False),
    sa.Column('gh_repo', sa.String(), nullable=False),
    sa.Column('gh_issue_number', sa.Integer(), nullable=False),
    sa.Column('gh_issue_node_id', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_source_last', sa.Enum('plane', 'github', name='sync_source'), nullable=False),
    sa.PrimaryKeyConstraint('plane_card_id'),
    sa.UniqueConstraint('gh_repo', 'gh_issue_number', name='uq_card_issue_link_repo_issue')
    )
    op.create_table('webhook_event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('plane', 'github', name='webhook_source'), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='webhook_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_event_log')
    op.drop_table('card_issue_link')
    op.execute('DROP TYPE webhook_status')
    op.execute('DROP TYPE webhook_source')
    op.execute('DROP TYPE sync_source')
    # ### end Alembic commands ###
