"""add_last_reminder_at

Revision ID: c015cc994f32
Revises: 6c902fdc0f2a
Create Date: 2026-05-26 15:32:14.444392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c015cc994f32'
down_revision: Union[str, Sequence[str], None] = '6c902fdc0f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pr_notification_state', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr_notification_state', 'last_reminder_at')
    # ### end Alembic commands ###
